% figure3.m
% Host extinction dynamics in the rg1_1CO parameter set at rho = 0.6:
% starting on the cooperator limit cycle, a few defectors are introduced
% and the population settles to a stable (defector) equilibrium.
%
% Panel 1 (figure 1): the cooperator limit cycle itself, in (H_U, V_C).
% Panel 2 (figure 2): H_U time series before and after the defector
%   introduction, showing the reduction in host extinction risk.
%
% Requires ../data/limitCycleStabilityData.mat (generated by
% cooperatorLimitCycleStability.m).

addpath('../functions')

r=5;
d= 60/108.9; %derived from latent period time
kappa=1;
mu1= 9.9*(10^(-6.5)); %derived from adsorption rate
mu2 = mu1^2;
xi = r/1000; %sets carrying capacity to 1000
lambda = 210; %from Turner and Chao paper
rho6 = 0.6;

params = [ mu1,mu2,r, d, kappa, lambda, xi,rho6];
opts = odeset('RelTol',1e-10,'AbsTol',1e-10);

% Initial condition: a point on the cooperator limit cycle
load("../data/limitCycleStabilityData.mat","CLCPoint")
lcPoint = CLCPoint;

%% First: cooperator limit cycle

% Run long enough to capture several periods, then trim to one using findpeaks
[~, lc_long] = ode45(@modelEqs, 0:0.1:2000, CLCPoint, opts, params);
[~, locs]    = findpeaks(lc_long(:, 5));   % peaks in V_C
lcOne        = lc_long(locs(end-1):locs(end), :);   % one period: peak to peak

% Look at only uninfected host, cooperator virus density
 HU_lc    = lcOne(:, 1);
 VC_lc = lcOne(:, 5);

figure(1); hold on
set(gcf, 'Renderer', 'painters')
coopColor = [0, 0.4470, 0.6980];   % #0072B2
plot([HU_lc; HU_lc(1)], [VC_lc; VC_lc(1)], 'k', 'LineWidth', 3)
xlabel('H_U', 'FontSize', 20)
ylabel('V_C', 'FontSize', 20)
box on
%% Next, introduction of a defector
tspan = 0:.1:100;
[tspan,lcPoint] = ode45(@modelEqs, tspan, lcPoint,opts, params);

% Introduce a small defector population (H_D, V_D) and continue integrating
defectorIntro = lcPoint(end,:) + [0 0 10 0 0 10];
tspan2 = 100.1:.1:700;
[tspan2,defectorIntro] = ode45(@modelEqs, tspan2, defectorIntro,opts, params);

figure(2)
set(gcf,'renderer', 'Painters')
plot(tspan,lcPoint(:,1),'LineWidth',3,'Color','k')
hold on; 
plot(tspan2,defectorIntro(:,1),'LineWidth',3,'Color','k')
xline(100,'Color','#D55E00','LineWidth',5)
xlim([0 600])
ylim([-50 850])
xlabel('time')
ylabel('H_U')
set(gca,'FontSize',16)