%% figure1_combinedBifurcation.m
% Combined bifurcation diagram across all three ecological regimes.
% Row 1: total host density (H_U + H_C + H_D + H_M)
% Row 2: total viral density (V_C + V_D)
% Row 3: total viral density — zoomed to coexistence (pink) region
% Columns: host poor (rl1) | host rich large burst (rg1_1CO) | host rich small burst (rg1_2CO)
%
% Requires ../data/verifiedBifurcations.mat (generated by verifyBifurcations.m)
% Note: plotEquilibria is a local function — must remain at end of file.

addpath('../functions')

%% Shared visual parameters
LW         = 3;
FS         = 16;
MS         = 8;
FAlpha     = 0.2;
yMax       = 2e6;
verts      = [1 2 3 4];
zoomWiggle = 0.10;   % fractional buffer on each side of zoom x-limits

% Host density y-limits: align 0 with viral density axis
% Viral ylim: [-20000, 7e5] → 0 sits 20000/720000 from bottom
yMaxHost = 3200;
yMinHost = -yMaxHost * 20000 / 7e5;

% Wong colorblind-friendly palette
% Equilibrium order from bifurcationGenerator: E, U, C1, C2, C3, D1, D2, D3, M
cVec = {'#FFFFFF',  ...  % 1: extinction
        '#009E73',  ...  % 2: uninfected (green)
        '#56B4E9',  ...  % 3: cooperator 1 (sky blue)
        '#0072B2',  ...  % 4: cooperator 2 (dark blue)
        '#56B4E9',  ...  % 5: cooperator 3 (sky blue)
        '#E69F00',  ...  % 6: defector 1 (orange)
        '#D55E00',  ...  % 7: defector 2 (vermillion)
        '#E69F00',  ...  % 8: defector 3 (orange)
        '#CC79A7'};      % 9: mixed (pink)

coopColor  = '#0072B2';
mixedColor = '#CC79A7';
defColor   = '#D55E00';

%% Load verified bifurcation vectors
vBifs = load('../data/verifiedBifurcations.mat');

%% Set up figure
figure(1)
clf
set(gcf, 'Position', [50 50 1400 1050], 'renderer', 'Painters')

%% =========================================================
%% COLUMN 1: Host poor regime (rl1)
%% =========================================================
load('../data/rl1_run.mat', 'stableCell', 'unStableCell', 'rhoVec', 'mu1', 'mu2', 'r', 'd', 'kappa', 'lambda', 'xi')

rl1_stable   = stableCell;
rl1_unstable = unStableCell;
rl1_rhoVec   = rhoVec;
rl1_params   = [mu1, mu2, r, d, kappa, lambda, xi];

rl1_collisions = mixedCollisions(rl1_params);
rl1_bifVec     = vBifs.rl1_bifVec;

% Zoom x-limits: collision bounds ± wiggle
rl1_zlo = rl1_collisions(1);
rl1_zhi = rl1_collisions(end);
rl1_zw  = zoomWiggle * (rl1_zhi - rl1_zlo);

% Background patches
rl1_blueBox   = [0                 -yMax; rl1_collisions(1) -yMax; rl1_collisions(1) yMax; 0                 yMax];
rl1_purpleBox = [rl1_collisions(1) -yMax; rl1_collisions(2) -yMax; rl1_collisions(2) yMax; rl1_collisions(1) yMax];
rl1_redBox    = [rl1_collisions(2) -yMax; 2                 -yMax; 2                 yMax; rl1_collisions(2) yMax];

for sp = [1, 4, 7]
    subplot(3,3,sp); hold on
    patch('Faces',verts,'Vertices',rl1_blueBox,   'FaceColor',coopColor,  'FaceAlpha',FAlpha,'EdgeColor','none')
    patch('Faces',verts,'Vertices',rl1_purpleBox, 'FaceColor',mixedColor, 'FaceAlpha',FAlpha,'EdgeColor','none')
    patch('Faces',verts,'Vertices',rl1_redBox,    'FaceColor',defColor,   'FaceAlpha',FAlpha,'EdgeColor','none')
end

for sp = [1, 4, 7]
    subplot(3,3,sp)
    for b = rl1_bifVec
        xline(b, ':k', 'LineWidth', 1)
    end
end

plotEquilibria(rl1_stable, rl1_unstable, rl1_rhoVec, cVec, 1, 4, 7, LW)

% No limit cycles for host poor regime

% Axis formatting
subplot(3,3,1)
xlim([rl1_rhoVec(1) 1]); ylim([yMinHost yMaxHost])
ylabel('total host density'); xlabel('\rho')
title('host poor'); set(gca,'FontSize',FS)

yMaxViral_rl1 = 3e4;
yMinViral_rl1 = -yMaxViral_rl1 * 20000 / 7e5;   % same 0-fraction as [-20000, 7e5]

subplot(3,3,4)
xlim([rl1_rhoVec(1) 1]); ylim([-20000 7e5])
yline(mu1/mu2, ':k', 'LineWidth', 2)
ylabel('total viral density'); xlabel('\rho')
set(gca,'FontSize',FS)

subplot(3,3,7)
xlim([rl1_zlo - rl1_zw, rl1_zhi + rl1_zw]); ylim([yMinViral_rl1 yMaxViral_rl1])
yline(mu1/mu2, ':k', 'LineWidth', 2)
ylabel('total viral density'); xlabel('\rho')
set(gca,'FontSize',FS)

%% =========================================================
%% COLUMN 2: Host rich, large burst regime (rg1_1CO)
%% =========================================================
load('../data/rg1_1CO_run.mat', 'stableCell', 'unStableCell', 'rhoVec', 'mu1', 'mu2', 'r', 'd', 'kappa', 'lambda', 'xi')
rg11_eqRhoVec = rhoVec;
load('../data/limitCycleStabilityData.mat', 'stabVec', 'allMaxes', 'allMins', 'rhoVec', 'limCycleHostMin', 'limCycleHostMax', 'rhoTransition')
rg11_LCrhoVec = rhoVec;
load('../data/defectorLimitCycleAmps.mat', 'defectorLimitCycleRhoVec', 'DLCMax', 'DLCMin', 'DLCMaxHostAmp', 'DLCMinHostAmp')

rg11_stable        = stableCell;
rg11_unstable      = unStableCell;
rg11_rhoVec        = [0.01 1];
rg11_params        = [mu1, mu2, r, d, kappa, lambda, xi];
rg11_stabVec       = stabVec;
rg11_allMaxes      = allMaxes;
rg11_allMins       = allMins;
lcHostMax          = limCycleHostMax;
lcHostMin          = limCycleHostMin;
rg11_DLCRho        = defectorLimitCycleRhoVec;
rg11_DLCMax        = DLCMax;
rg11_DLCMin        = DLCMin;
rg11_DLCMaxHostAmp = DLCMaxHostAmp;
rg11_DLCMinHostAmp = DLCMinHostAmp;

rg11_stableLCrho = rg11_LCrhoVec(rg11_stabVec == 2);

rg11_collisions = mixedCollisions(rg11_params);
rg11_bifVec     = vBifs.rg11_bifVec;

% Zoom x-limits: collision bounds ± wiggle
rg11_zlo = rg11_collisions(1);
rg11_zhi = rg11_collisions(end);
rg11_zw  = zoomWiggle * (rg11_zhi - rg11_zlo);

% Background patches
rg11_blueBox = [0                  -yMax; rhoTransition      -yMax; rhoTransition      yMax; 0                  yMax];
rg11_pinkBox = [rhoTransition      -yMax; rg11_collisions(2) -yMax; rg11_collisions(2) yMax; rhoTransition      yMax];
rg11_redBox  = [rg11_collisions(2) -yMax; 2                  -yMax; 2                  yMax; rg11_collisions(2) yMax];

for sp = [2, 5, 8]
    subplot(3,3,sp); hold on
    patch('Faces',verts,'Vertices',rg11_blueBox, 'FaceColor',coopColor, 'FaceAlpha',FAlpha,'EdgeColor','none')
    patch('Faces',verts,'Vertices',rg11_pinkBox, 'FaceColor',mixedColor,'FaceAlpha',FAlpha,'EdgeColor','none')
    patch('Faces',verts,'Vertices',rg11_redBox,  'FaceColor',defColor,  'FaceAlpha',FAlpha,'EdgeColor','none')
end

for sp = [2, 5, 8]
    subplot(3,3,sp)
    for b = rg11_bifVec
        xline(b, ':k', 'LineWidth', 1)
    end
end

% Single vs double infection threshold
for sp = [5, 8]
    subplot(3,3,sp)
    yline(mu1/mu2, ':k', 'LineWidth', 2)
end

plotEquilibria(rg11_stable, rg11_unstable, rg11_eqRhoVec, cVec, 2, 5, 8, LW)

% Cooperator LC: host (sp=2), viral (sp=5, sp=8)
subplot(3,3,2)
plot(rg11_stableLCrho(1:8:end), lcHostMax.*ones(1,length(rg11_stableLCrho(1:8:end))), ...
    'o', 'Color',cVec{4}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{4})
plot(rg11_stableLCrho(1:8:end), lcHostMin.*ones(1,length(rg11_stableLCrho(1:8:end))), ...
    'o', 'Color',cVec{4}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{4})

% sp=5: original subsampling
subplot(3,3,5)
plot(rg11_stableLCrho(1:8:end), rg11_allMaxes(5).*ones(1,length(rg11_stableLCrho(1:8:end))), ...
    'o', 'Color',cVec{4}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{4})
plot(rg11_stableLCrho(1:8:end), rg11_allMins(5).*ones(1,length(rg11_stableLCrho(1:8:end))), ...
    'o', 'Color',cVec{4}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{4})

% sp=8: 3 evenly-spaced markers within the stable LC rho range visible in zoom
rg11_zoom_crho = rg11_stableLCrho(rg11_stableLCrho >= (rg11_zlo - rg11_zw) & ...
                                   rg11_stableLCrho <= (rg11_zhi + rg11_zw));
if ~isempty(rg11_zoom_crho)
    rho_c3 = linspace(rg11_zoom_crho(1), rg11_zoom_crho(end), 3);
    subplot(3,3,8)
    plot(rho_c3, rg11_allMaxes(5).*ones(size(rho_c3)), 'o', 'Color',cVec{4}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{4})
    plot(rho_c3, rg11_allMins(5).*ones(size(rho_c3)),  'o', 'Color',cVec{4}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{4})
end

% Defector LC: host (sp=2), viral (sp=5, sp=8)
subplot(3,3,2)
plot(rg11_DLCRho(1:4:end), rg11_DLCMaxHostAmp(1:4:end), 'o', 'Color',cVec{7}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{7})
plot(rg11_DLCRho(1:4:end), rg11_DLCMinHostAmp(1:4:end), 'o', 'Color',cVec{7}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{7})

% sp=5: original subsampling
subplot(3,3,5)
plot(rg11_DLCRho(1:4:end), rg11_DLCMax(1:4:end,3), 'o', 'Color',cVec{7}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{7})
plot(rg11_DLCRho(1:4:end), rg11_DLCMin(1:4:end,3), 'o', 'Color',cVec{7}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{7})


% Axis formatting
subplot(3,3,2)
xlim([rg11_rhoVec(1) 1]); ylim([yMinHost yMaxHost])
xlabel('\rho')
title('host rich & large burst size'); set(gca,'FontSize',FS)

subplot(3,3,5)
xlim([rg11_rhoVec(1) 1]); ylim([-20000 7e5])
xlabel('\rho'); set(gca,'FontSize',FS)

subplot(3,3,8)
xlim([rg11_zlo - rg11_zw, rg11_zhi + rg11_zw]); ylim([-20000 7e5])
xlabel('\rho'); set(gca,'FontSize',FS)

%% =========================================================
%% COLUMN 3: Host rich, small burst regime (rg1_2CO)
%% =========================================================
load('../data/rg1_2CO_run.mat', 'stableCell', 'unStableCell', 'rhoVec', 'mu1', 'mu2', 'r', 'd', 'kappa', 'lambda', 'xi')
load('../data/mixedLimitCycles.mat', 'testingRho', 'storePopMaxVec', 'storePopMinVec')

rg12_stable   = stableCell;
rg12_unstable = unStableCell;
rg12_rhoVec   = rhoVec;

rg12_testingRho     = testingRho;
rg12_storePopMaxVec = storePopMaxVec;
rg12_storePopMinVec = storePopMinVec;

rg12_params = [mu1, mu2, r, d, kappa, lambda, xi];
[ecColl_rg12, edColl_rg12] = mixedCollisions(rg12_params);
rhoTCM = ecColl_rg12(1);
tmp = load('../data/homoclinicRhoData.mat', 'rhoHC'); rhoHC_rg12 = tmp.rhoHC;

numS   = (-2*mu1^3 - 9*mu1*mu2*r + 2*sqrt((mu1^2 + 3*mu2*r)^3)) * d*kappa*xi;
denomS = 2*mu2*r^2 * (mu1^2 + 4*mu2*r) * lambda;
rhoS   = numS / denomS;

rg12_bifVec = vBifs.rg12_bifVec;

% Zoom x-limits: all E_M collision bounds ± wiggle
allColl_rg12 = sort([ecColl_rg12(:); edColl_rg12(:)]);
rg12_zlo = allColl_rg12(1);
rg12_zhi = allColl_rg12(end);
rg12_zw  = zoomWiggle * (rg12_zhi - rg12_zlo);

% Background patches
rg12_blueBox   = [0      -yMax; rhoTCM     -yMax; rhoTCM     yMax; 0      yMax];
rg12_purpleBox = [rhoTCM -yMax; rhoHC_rg12 -yMax; rhoHC_rg12 yMax; rhoTCM yMax];
rg12_redBox    = [rhoS   -yMax; 2           -yMax; 2           yMax; rhoS   yMax];

for sp = [3, 6, 9]
    subplot(3,3,sp); hold on
    patch('Faces',verts,'Vertices',rg12_blueBox,   'FaceColor',coopColor,  'FaceAlpha',FAlpha,'EdgeColor','none')
    patch('Faces',verts,'Vertices',rg12_purpleBox, 'FaceColor',mixedColor, 'FaceAlpha',FAlpha,'EdgeColor','none')
    patch('Faces',verts,'Vertices',rg12_redBox,    'FaceColor',defColor,   'FaceAlpha',FAlpha,'EdgeColor','none')
end

for sp = [3, 6, 9]
    subplot(3,3,sp)
    for b = rg12_bifVec
        xline(b, ':k', 'LineWidth', 1)
    end
end

% Single vs double infection threshold
for sp = [6, 9]
    subplot(3,3,sp)
    yline(mu1/mu2, ':k', 'LineWidth', 2)
end

plotEquilibria(rg12_stable, rg12_unstable, rg12_rhoVec, cVec, 3, 6, 9, LW)

% Mixed LC: host (sp=3), viral (sp=6, sp=9)
subplot(3,3,3)
plot(rg12_testingRho, rg12_storePopMaxVec(:,1), 'o', 'Color',cVec{9}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{9})
plot(rg12_testingRho, rg12_storePopMinVec(:,1), 'o', 'Color',cVec{9}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{9})

for sp = [6, 9]
    subplot(3,3,sp)
    plot(rg12_testingRho, rg12_storePopMaxVec(:,2), 'o', 'Color',cVec{9}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{9})
    plot(rg12_testingRho, rg12_storePopMinVec(:,2), 'o', 'Color',cVec{9}, 'MarkerSize',MS, 'MarkerFaceColor',cVec{9})
end

% Axis formatting
subplot(3,3,3)
xlim([rg12_rhoVec(1) 1]); ylim([yMinHost yMaxHost])
xlabel('\rho')
title('host rich & small burst size'); set(gca,'FontSize',FS)

subplot(3,3,6)
xlim([rg12_rhoVec(1) 1]); ylim([-20000 7e5])
xlabel('\rho'); set(gca,'FontSize',FS)

subplot(3,3,9)
xlim([rg12_zlo - rg12_zw, rg12_zhi + rg12_zw]); ylim([-20000 7e5])
xlabel('\rho'); set(gca,'FontSize',FS)

%% =========================================================
%% LOCAL FUNCTION — must remain at end of file
%% =========================================================

function plotEquilibria(stbl, unstbl, rhoVec, cVec, spHost, spViral, spCoex, LW)
    setDist = max(rhoVec(2:end) - rhoVec(1:end-1));
    for i = 2:size(stbl, 2)  % skip extinction (i=1)
        for stab = 1:2
            if stab == 2; data = stbl{i};   ls = '-';
            else;         data = unstbl{i}; ls = '--'; end
            if isempty(data), continue; end

            % Find discontinuities in rho
            diffs = data(2:end,7) - data(1:end-1,7);
            if sum(diffs > setDist) > 0
                jmp  = find(diffs > setDist) + 1;
                segs = {1:jmp-1, jmp:size(data,1)};
            else
                segs = {1:size(data,1)};
            end

            for s = 1:length(segs)
                seg        = segs{s};
                totalHost  = sum(data(seg, 1:4), 2);
                totalViral = sum(data(seg, 5:6), 2);

                subplot(3,3,spHost)
                plot(data(seg,7), totalHost,  ls, 'Color', cVec{i}, 'LineWidth', LW)
                hold on

                subplot(3,3,spViral)
                plot(data(seg,7), totalViral, ls, 'Color', cVec{i}, 'LineWidth', LW)
                hold on

                subplot(3,3,spCoex)
                plot(data(seg,7), totalViral, ls, 'Color', cVec{i}, 'LineWidth', LW)
                hold on
            end
        end
    end
end
